[package]
name = "io_rust"
version = "0.1.0"
edition = "2021"

[workspace]

members = [
  "envar",
  "io_csv",    
  "io_json", 
  "io_xml", 
  "io_yml", 
  "pv_1d", 
  "pv_time_series"
]

[dependencies]
